name: Solar System Workflow

on:
  workflow_dispatch: # Allows manual triggering
  push: # Trigger on pushes
    branches:
      - main # Only trigger for 'main'
      - "feature/*" # Or branches matching 'feature/*'

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version - 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test
